
#ifndef cudaErrorMemoryValueTooLarge
#define cudaErrorMemoryValueTooLarge CUBLAS_STATUS_INTERNAL_ERROR
#endif

#ifndef cudaErrorInvalidValue
#define cudaErrorInvalidValue CUBLAS_STATUS_INVALID_VALUE
#endif